name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          globs: "**/*.md"

      - name: Check formatting
        run: make format-check

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    env:
      GTEST_COLOR: "1"

    steps:
      - uses: actions/checkout@v7

      - name: Test
        run: make test
